CREATE TABLE public.training_readiness (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  calendar_date date NOT NULL,
  "timestamp" timestamptz NOT NULL,
  device_id bigint NULL,
  level text NULL,
  feedback_long text NULL,
  feedback_short text NULL,
  score integer NULL,
  sleep_score integer NULL,
  sleep_score_factor_percent integer NULL,
  sleep_score_factor_feedback text NULL,
  recovery_time integer NULL,
  recovery_time_factor_percent integer NULL,
  recovery_time_factor_feedback text NULL,
  acwr_factor_percent integer NULL,
  acwr_factor_feedback text NULL,
  acute_load integer NULL,
  stress_history_factor_percent integer NULL,
  stress_history_factor_feedback text NULL,
  hrv_factor_percent integer NULL,
  hrv_factor_feedback text NULL,
  hrv_weekly_average integer NULL,
  sleep_history_factor_percent integer NULL,
  sleep_history_factor_feedback text NULL,
  valid_sleep boolean NULL,
  input_context text NULL,
  recovery_time_change_phrase text NULL,
  synced_at timestamptz NULL,
  CONSTRAINT training_readiness_calendar_date_timestamp_key
    UNIQUE (calendar_date, "timestamp")
);
